import namor from 'namor';
import './table.css';

const range = len => {
  const arr = [];
  for (let i = 0; i < len; i++) {
    arr.push(i);
  }
  return arr;
};

const newPerson = () => {
  const statusChance = Math.random();
  return {
    firstName: namor.generate({ words: 1, numbers: 0 }),
    lastName: namor.generate({ words: 1, numbers: 0 }),
    age: Math.floor(Math.random() * 30),
    visits: Math.floor(Math.random() * 100),
    progress: Math.floor(Math.random() * 100),
    status: statusChance > 0.66 ? 'relationship' : statusChance > 0.33 ? 'complicated' : 'single',
  };
};

export function makeData(len = 5553) {
  return range(len).map(d => {
    return {
      ...newPerson(),
      children: range(10).map(newPerson),
    };
  });
}

export function trainingData() {
  const trainings = [
    { name: 'AWS' },
    { name: 'Active Directory' },
    { name: 'Asterisk' },
    { name: 'BICSI' },
    { name: 'Cisco' },
    { name: 'ColdFusion' },
    { name: 'Customer Service' },
    { name: 'Cyber Security' },
    { name: 'DB Analysis Tools' },
    { name: 'Database Management' },
    { name: 'DevOps' },
    { name: 'FOCUS' },
    { name: 'Firewall' },
    { name: 'IPS' },
    { name: 'ISC CISSP' },
    { name: 'ISC CSSLP' },
    { name: 'JavaScript' },
    { name: 'Juniper' },
    { name: 'Leadership' },
    { name: 'Linux Admin' },
    { name: 'McAfee' },
    { name: 'Microsoft Office' },
    { name: 'NetApp' },
    { name: 'Netcool' },
    { name: 'Network/System Design' },
    { name: 'Oracle' },
    { name: 'Program Management' },
    { name: 'Puppet Labs' },
    { name: 'RMF' },
    { name: 'Red Hat Labs' },
    { name: 'Remedy' },
    { name: 'Routing/Switching' },
    { name: 'SCCM' },
    { name: 'SQL' },
    { name: 'Satellite/RF Theory' },
    { name: 'SharePoint' },
    { name: 'VMWare' },
    { name: 'VTC Systems' },
    { name: 'Windows Admin' },
    { name: 'Windows Desktop' },
    { name: 'Windows Server' },
  ];
  return trainings;
}
export function certData() {
  const certifications = [
    { name: 'A+' },
    { name: 'Agile' },
    { name: 'AWS' },
    { name: 'BICSI' },
    { name: 'CAP' },
    { name: 'CCNA' },
    { name: 'CCNE' },
    { name: 'CCNP' },
    { name: 'CISSP' },
    { name: 'Cloudera CDH4 Admin' },
    { name: 'Cloudera CDH4 Developer' },
    { name: 'CSM' },
    { name: 'CTNS' },
    { name: 'GSLC' },
    { name: 'HDI' },
    { name: 'INCOSE CSEP' },
    { name: 'ISSA' },
    { name: 'ITIL' },
    { name: 'Lean Six Sigma' },
    { name: 'MCSA' },
    { name: 'MCSE' },
    { name: 'Network+' },
    { name: 'OCP DBA' },
    { name: 'Oracle' },
    { name: 'PMP' },
    { name: 'Security+' },
    { name: 'Sharepoint' },
    { name: 'Splunk' },
    { name: 'VMWare' },
  ];
  return certifications;
}

export function careerTrackData() {
  const careerTracks = [
    {
      careerTrackName: 'Cyber IA',
      programName: 'DoD Space Program',
      positionTitle: '',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Cyber IA',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Cyber IA',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Cyber IT',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Cyber IT',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Cyber IT',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Cyber IT',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Cyber IT',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Database Admin',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Database Admin',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Deskside/Field Services',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Deskside/Field Services',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'TS',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Deskside/Field Services',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Deskside/Field Services',
      programName: 'DoS Nuclear Defense System',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Keeley Deleon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Deskside/Field Services',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },

    {
      careerTrackName: 'Network Engineering',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Network Engineering',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 1,
      certification: '',
    },

    {
      careerTrackName: 'Network Engineering',
      programName: 'DoD Space Program',
      positionTitle: '',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Network Engineering',
      programName: 'DoD Space Program',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Network Engineering',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Network Engineering',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'TS',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoD Space Program',
      positionTitle: '',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoD Space Program',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DoD Space Program',
      positionTitle: '',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DoD Space Program',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 1,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI CI POLY',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Software Development',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Software Development',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Software Development',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Software Development',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },

    {
      careerTrackName: 'Systems Admin',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Systems Admin',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI CI POLY',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Systems Admin',
      programName: 'DHS Satellite Network',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },

    {
      careerTrackName: 'Systems Admin',
      programName: 'DoJ Networks',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 4,
      certification: '',
    },

    {
      careerTrackName: 'Systems Admin',
      programName: 'FBI Case Management System',
      positionTitle: '',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 4,
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'Department of Homeland Security Network',
      positionTitle: 'Senior Splunk System Engineer',
      locationName: 'Washington DC',
      clearanceLevel: 'Secret',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: 'Splunk',
    },
    {
      careerTrackName: 'System Admin',
      programName: 'AWS Technical Support Program',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'Secret',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'AWS Technical Support Program',
      positionTitle: '',
      locationName: 'Washington DC',
      clearanceLevel: 'Secret',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
  ];

  return careerTracks;
}

export function positionSearchData() {
  const careerTracks = [
    {
      positionTitle: 'IA Supervisor',
      careerTrackName: 'Cyber IA',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Mid IA Analyst',
      careerTrackName: 'Cyber IA',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'IA Supervisor',
      careerTrackName: 'Cyber IA',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'IA Manager',
      careerTrackName: 'Cyber IA',
      programName: 'DHS Satellite Network',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      positionTitle: 'IA Supervisor',
      careerTrackName: 'Cyber IT',
      programName: 'DHS Satellite Network',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Cyber IT Supervisor',
      careerTrackName: 'Cyber IT',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Cyber IT Manager',
      careerTrackName: 'Cyber IT',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      positionTitle: 'Cyber IT Manager',
      careerTrackName: 'Cyber IT',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      positionTitle: 'Cyber IT Manager',
      careerTrackName: 'Cyber IT',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      positionTitle: 'Oracle DBA',
      careerTrackName: 'Database Admin',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'SQL Server DBA',
      careerTrackName: 'Database Admin',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Jr. Field Technician',
      careerTrackName: 'Deskside/Field Services',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 1,
      certification: '',
    },
    {
      positionTitle: 'Jr. Field Technician',
      careerTrackName: 'Deskside/Field Services',
      programName: 'FBI Case Management System',
      locationName: 'Washington DC',
      clearanceLevel: 'TS',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 1,
      certification: '',
    },
    {
      positionTitle: 'Field Technician Supervisor',
      careerTrackName: 'Deskside/Field Services',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Field Technician Supervisor',
      careerTrackName: 'Deskside/Field Services',
      programName: 'DoS Nuclear Defense System',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Keeley Deleon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Field Technician Manager',
      careerTrackName: 'Deskside/Field Services',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 3,
      certification: '',
    },
    {
      positionTitle: 'Field Technician Manager',
      careerTrackName: 'Deskside/Field Services',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 3,
      certification: '',
    },
    {
      positionTitle: 'Field Technician Manager',
      careerTrackName: 'Deskside/Field Services',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },

    {
      positionTitle: 'Help Desk Support Supervisor',
      careerTrackName: 'Help Desk',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Help Desk Support Supervisor',
      careerTrackName: 'Help Desk',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Jr. Network Engineer',
      careerTrackName: 'Network Engineering',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 1,
      certification: '',
    },
    {
      positionTitle: 'Jr. Network Engineer',
      careerTrackName: 'Network Engineering',
      programName: 'DHS Satellite Network',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 1,
      certification: '',
    },

    {
      positionTitle: 'Sr. Network Analyst',
      careerTrackName: 'Network Engineering',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      positionTitle: 'Sr. Network Analyst',
      careerTrackName: 'Network Engineering',
      programName: 'DoD Space Program',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },

    {
      positionTitle: 'Network Engineer Supervisor',
      careerTrackName: 'Network Engineering',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },

    {
      positionTitle: 'Network Security Engineer',
      careerTrackName: 'Network Engineering',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },

    {
      positionTitle: 'Network Security Engineer',
      careerTrackName: 'Network Engineering',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      locationName: 'Washington DC',
      clearanceLevel: 'TS',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoD Space Program',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DoD Space Program',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 1,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 1,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI CI POLY',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DHS Satellite Network',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Software Development',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 1,
      certification: '',
    },

    {
      careerTrackName: 'Software Development',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 1,
      certification: '',
    },

    {
      careerTrackName: 'Software Development',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Software Development',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Software Development',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },

    {
      careerTrackName: 'Systems Admin',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Systems Admin',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI CI POLY',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      certification: '',
    },
    {
      careerTrackName: 'Systems Admin',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      certification: '',
    },

    {
      careerTrackName: 'Systems Admin',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 4,
      certification: '',
    },

    {
      careerTrackName: 'Systems Admin',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 4,
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI CI POLY',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Systems Engineering',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Systems Engineering',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      certification: '',
    },

    {
      careerTrackName: 'Systems Engineering',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'Department of Homeland Security Network',
      positionTitle: 'Senior Splunk System Engineer',
      locationName: 'Washington DC',
      clearanceLevel: 'Secret',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: 'Splunk',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'Department of Homeland Security Network',
      positionTitle: 'Senior Splunk System Manager',
      locationName: 'Washington DC',
      clearanceLevel: 'Secret',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      certification: 'Splunk',
    },
  ];

  return careerTracks;
}

export function enhancementSearchData() {
  const careerEnhancements = [
    {
      positionTitle: 'AWS Adminstrator',
      careerTrackName: 'Systems Admin',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'Secret',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: 'AWS',
    },
    {
      positionTitle: '',
      careerTrackName: 'Cyber IA',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: '',
      careerTrackName: 'Cyber IA',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: 'IA Supervisor Proposal Position',
      careerTrackName: 'Cyber IA',
      programName: 'AWS Technical Support Program',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: 'Cyber IT Future Position',
      careerTrackName: 'Cyber IT',
      programName: 'DHS Satellite Network',
      locationName: 'Washington DC',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: '',
      careerTrackName: 'Cyber IT',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: '',
      careerTrackName: 'Cyber IT',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: '',
      careerTrackName: 'Cyber IT',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: 'Oracle DBA Coverage',
      careerTrackName: 'Database Admin',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      clearanceLevel: 'DOJ SUITABILITY/ TS',
      programManagerName: 'Clarence Hodson',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      positionTitle: 'Field Technician Coverage',
      careerTrackName: 'Deskside/Field Services',
      programName: 'FBI Case Management System',
      locationName: 'Washington DC',
      clearanceLevel: 'TS',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 1,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: '',
      careerTrackName: 'Deskside/Field Services',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: '',
      careerTrackName: 'Deskside/Field Services',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      positionTitle: '',
      careerTrackName: 'Help Desk',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: '',
      careerTrackName: 'Network Engineering',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: 'Network Security Engineer Proposal Position',
      careerTrackName: 'Network Engineering',
      programName: 'DoD Space Program',
      locationName: 'Washington DC',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: '',
      careerTrackName: 'Network Engineering',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      positionTitle: 'Program Ops Proposal Position',
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      locationName: 'Washington DC',
      clearanceLevel: 'TS',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 1,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program Ops (Technical)',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 1,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI CI POLY',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      careerTrackName: 'Program/Project Management',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Program/Project Management',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Software Development',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 1,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      careerTrackName: 'Software Development',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'SECRET',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 1,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Software Development',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Software Development',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Systems Admin',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI CI POLY',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Systems Admin',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Systems Admin',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 4,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI CI POLY',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      careerTrackName: 'Systems Engineering',
      programName: 'DoD Space Program',
      locationName: 'Fort Belvoir VA',
      clearanceLevel: 'TS/SCI',
      programManagerName: 'Dodie Crowther',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
    {
      careerTrackName: 'Systems Engineering',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      careerTrackName: 'Systems Engineering',
      programName: 'DHS Satellite Network',
      locationName: 'Chantilly VA',
      clearanceLevel: 'EOD SUITABILITY / SECRET',
      programManagerName: 'Tanisha Helms',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      careerTrackName: 'Systems Engineering',
      programName: 'AWS Technical Support Program',
      locationName: 'National Harbor MD',
      clearanceLevel: 'EOD SUITABILITY / TS/SCI',
      programManagerName: 'Eladia Calderon',
      careerTrackTier: 2,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },

    {
      careerTrackName: 'Systems Engineering',
      programName: 'FBI Case Management System',
      locationName: 'Chantilly VA',
      clearanceLevel: 'TS/SCI FSP',
      programManagerName: 'Bryon Sprague',
      careerTrackTier: 3,
      enhancementType: 1,
      futureDate: '9/1/2020',
      duration: '1 month',
      certification: '',
    },
  ];

  return careerEnhancements;
}

export function employeesWithSelectedCareerTrackData() {
  const employees = [
    {
      employeeName: 'Sharyn Ballard',
      careerTrackName: 'Systems Admin',
      careerTrackTier: 2,
      desiredCareerTrack: 'Systems Engineering',
      desiredCareerTrackCompletionDate: '7/1/2020',
      inProgressCertifications: {
        progress: 'Green',
        name: 'Security+',
      },
      inProgressTrainings: {
        progress: 'Green',
        name: 'Leadership',
      },
      currentGoal: 'Career Track Change to Systems Engineering',
      position: 'Linux System Admin',
    },
    {
      employeeName: 'Romeo Thompson',
      careerTrackName: 'Program Ops (Technical)',
      careerTrackTier: 2,
      desiredCareerTrack: 'Program Ops (Technical) Tier 3',
      desiredCareerTrackCompletionDate: '4/17/2020',
      inProgressCertifications: {
        progress: 'Red',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Red',
        name: 'Leadership',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Chere Nance',
      careerTrackName: 'Program Ops (Technical)',
      careerTrackTier: 2,
      desiredCareerTrack: 'Program Ops (Technical) Tier 3',
      desiredCareerTrackCompletionDate: '5/21/2020',
      inProgressCertifications: {
        progress: 'Green',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Red',
        name: 'Leadership',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Kami Najera',
      careerTrackName: 'Program Ops (Technical)',
      careerTrackTier: 2,
      desiredCareerTrack: 'Program Ops (Technical) Tier 3',
      desiredCareerTrackCompletionDate: '5/27/2020',
      inProgressCertifications: {
        progress: 'Red',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Green',
        name: 'Database',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Darryl Merryman',
      careerTrackName: 'Program/Project Management',
      careerTrackTier: 3,
      desiredCareerTrack: 'Program/Project Management Tier 4',
      desiredCareerTrackCompletionDate: '6/1/2020',
      inProgressCertifications: {
        progress: 'Red',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Green',
        name: 'Programming',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Brigitte Weiland',
      careerTrackName: 'Program Ops (Technical)',
      careerTrackTier: 2,
      desiredCareerTrack: 'Program Ops (Technical) Tier 3',
      desiredCareerTrackCompletionDate: '6/11/2020',
      inProgressCertifications: {
        progress: 'Green',
        name: 'Security+',
      },
      inProgressTrainings: {
        progress: 'Green',
        name: 'Database',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Emmitt Dugas',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      desiredCareerTrack: 'Software Development Tier 3',
      desiredCareerTrackCompletionDate: '6/23/2020',
      inProgressCertifications: {
        progress: 'Red',
        name: 'Oracle',
      },
      inProgressTrainings: {
        progress: 'Yellow',
        name: 'Leadership',
      },
      currentGoal: '',
      position: '',
    },
    // {
    //   employeeName: 'August Stanger',
    //   careerTrackName: 'Software Development',
    //   careerTrackTier: 2,
    //   desiredCareerTrack: 'Software Development Tier 3',
    //   desiredCareerTrackCompletionDate: '7/17/2020',
    //   inProgressCertifications: {
    //     progress: 'Red',
    //     name: 'AWS',
    //   },
    //   inProgressTrainings: {
    //     progress: 'Green',
    //     name: 'Programming',
    //   },
    //   currentGoal: '',
    // },
    {
      employeeName: 'Chia Villalba',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      desiredCareerTrack: 'Software Development Tier 3',
      desiredCareerTrackCompletionDate: '7/20/2020',
      inProgressCertifications: {
        progress: 'Yellow',
        name: 'Security+',
      },
      inProgressTrainings: {
        progress: 'Green',
        name: 'Leadership',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Hipolito Gooden',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      desiredCareerTrack: 'Software Development Tier 3',
      desiredCareerTrackCompletionDate: '7/25/2020',
      inProgressCertifications: {
        progress: 'Green',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Red',
        name: 'Database',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Enoch Hector',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      desiredCareerTrack: 'Software Development Tier 3',
      inProgressCertifications: {
        progress: 'Green',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Yellow',
        name: 'Leadership',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Nicolas Hadlock',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      desiredCareerTrack: 'Software Development Tier 3',
      inProgressCertifications: {
        progress: 'Yellow',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Yellow',
        name: 'Leadership',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Brock Brauer',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      desiredCareerTrack: 'Software Development Tier 3',
      inProgressCertifications: {
        progress: 'Yellow',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Yellow',
        name: 'Programming',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Phyliss Kaplan',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      desiredCareerTrack: 'Software Development Tier 3',
      inProgressCertifications: {
        progress: 'Red',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Yellow',
        name: 'Database',
      },
      currentGoal: '',
      position: '',
    },
    {
      employeeName: 'Nickie Buie',
      careerTrackName: 'Systems Admin',
      careerTrackTier: 1,
      desiredCareerTrack: 'Systems Admin Tier 2',
      inProgressCertifications: {
        progress: 'Green',
        name: 'AWS',
      },
      inProgressTrainings: {
        progress: 'Yellow',
        name: 'Leadership',
      },
      currentGoal: '',
      position: '',
    },
  ];
  return employees;
}

export function programEmployees() {
  const employees = [
    {
      progressStatus: 'Yellow',
      employeeName: 'Sharyn Ballard',
      locationName: 'Washington, DC',
      careerTrackName: 'Systems Admin',
      careerTrackTier: 2,
      currentStatus: 'Career Track Change Expected: 7/1/2020',
      position: 'Linux System Admin',
    },
    {
      progressStatus: 'Red',
      employeeName: 'Romeo Thompson',
      locationName: 'Washington, DC',
      careerTrackName: 'Program Ops (Technical)',
      careerTrackTier: 2,
      progressInformation: 'Applied to Position',
      currentStatus: 'Interested in Growth',
      position: '',
    },
    {
      progressStatus: 'Red',
      employeeName: 'Chere Nance',
      locationName: 'Washington, DC',
      careerTrackName: 'Program Ops (Technical)',
      careerTrackTier: 2,
      progressInformation: 'Interested in Career Enhancement Opportunity',
      currentStatus: 'Interested in Growth',
      position: '',
    },
    {
      progressStatus: 'Yellow',
      employeeName: 'Kami Najera',
      locationName: 'Washington, DC',
      careerTrackName: 'Program Ops (Technical)',
      careerTrackTier: 2,
      currentStatus: 'Location Change to California',
      position: '',
    },
    {
      progressStatus: 'Red',
      employeeName: 'Darryl Merryman',
      locationName: 'Washington, DC',
      careerTrackName: 'Program/Project Management',
      careerTrackTier: 3,
      progressInformation: 'Selected a New Primary Career Track',
      currentStatus: 'Losing Coverage: 7/1/2020',
      position: '',
    },
    {
      progressStatus: 'Yellow',
      employeeName: 'Brigitte Weiland',
      locationName: 'Washington, DC',
      careerTrackName: 'Program Ops (Technical)',
      careerTrackTier: 2,
      currentStatus: '',
      position: '',
    },
    {
      progressStatus: 'Yellow',
      employeeName: 'Emmitt Dugas',
      locationName: 'Washington, DC',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      currentStatus: '',
      position: '',
    },
    // {
    //   progressStatus: 'Yellow',
    //   employeeName: 'August Stanger',
    //   locationName: 'Washington, DC',
    //   careerTrackName: 'Software Development',
    //   careerTrackTier: 2,
    // },
    {
      progressStatus: 'Green',
      employeeName: 'Chia Villalba',
      locationName: 'Washington, DC',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      currentStatus: '',
      position: '',
    },
    {
      progressStatus: 'Red',
      employeeName: 'Hipolito Gooden',
      locationName: 'Washington, DC',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      progressInformation: 'Showed interest in Splunk Training',
      currentStatus: '',
      position: '',
    },
    {
      progressStatus: 'Yellow',
      employeeName: 'Enoch Hector',
      locationName: 'Washington, DC',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      currentStatus: '',
      position: '',
    },
    {
      progressStatus: 'Red',
      employeeName: 'Nicolas Hadlock',
      locationName: 'Washington, DC',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      progressInformation: 'Showed interest in Splunk Training',
      currentStatus: '',
      position: '',
    },
    {
      progressStatus: 'Red',
      employeeName: 'Brock Brauer',
      locationName: 'Washington, DC',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      progressInformation: 'Interested in Career Enhancement Opportunity',
      currentStatus: '',
      position: '',
    },
    {
      progressStatus: 'Red',
      employeeName: 'Phyliss Kaplan',
      locationName: 'Washington, DC',
      careerTrackName: 'Software Development',
      careerTrackTier: 2,
      progressInformation: 'Applied to Position',
      currentStatus: '',
      position: '',
    },
    {
      progressStatus: 'Yellow',
      employeeName: 'Nickie Buie',
      locationName: 'Washington, DC',
      careerTrackName: 'Systems Admin',
      careerTrackTier: 1,
      currentStatus: '',
      position: '',
    },
  ];
  return employees;
}

export function employeeSearch() {
  const employees = [
    {
      employeeId: 1,
      employeeName: 'Dorris Vaught',
      clearanceLevel: 'NO-CLRNC',
      careerTrackName: 'Cyber IA Tier 2',
      programName: 'AWS Technical Support Program',
      locationName: 'Chantilly VA',
      programManagerName: 'Dodie Crowther',
      interestedIn: 'Growth',
      certification: '',
      position: '',
    },
    {
      employeeId: 2,
      employeeName: 'Kris Shotwell',
      clearanceLevel: 'INTERIM TOP SECRET',
      careerTrackName: 'Cyber IA Tier 1',
      programName: 'DoD Space Program',
      locationName: 'National Harbor MD',
      programManagerName: 'Eladia Calderon',
      interestedIn: 'Location Change: Washington DC',
      certification: '',
      position: '',
    },
    {
      employeeId: 3,
      employeeName: 'Long Hudspeth',
      clearanceLevel: 'TS/SCI',
      careerTrackName: 'Cyber IA Tier 2',
      programName: 'DHS Satellite Network',
      locationName: 'National Harbor MD',
      programManagerName: 'Tanisha Helms',
      interestedIn: 'Open Position: Losing Coverage 3/1/2020',
      certification: '',
      position: '',
    },
    {
      employeeId: 4,
      employeeName: 'Vincenzo Whiteley',
      clearanceLevel: 'TOP SECRET',
      careerTrackName: 'Cyber IA Tier 1',
      programName: 'DoJ Networks',
      locationName: 'Washington DC',
      programManagerName: 'Cletus Hodson',
      interestedIn: 'New Career Track: Software Development',
      certification: '',
      position: '',
    },
    {
      employeeId: 5,
      employeeName: 'Reyes Holmes',
      clearanceLevel: 'TOP SECRET',
      careerTrackName: 'Cyber IA Tier 1',
      programName: 'DoS Nuclear Defense System',
      locationName: 'Fort Belvoir VA',
      programManagerName: 'Bryon Sprague',
      interestedIn: '',
      certification: '',
      position: '',
    },
    {
      employeeId: 6,
      employeeName: 'Deedra Bosch',
      clearanceLevel: 'TOP SECRET',
      careerTrackName: 'Cyber IA Tier 1',
      programName: 'FBI Case Management System',
      locationName: 'Fort Belvoir VA',
      programManagerName: 'Keeley Deleon',
      interestedIn: '',
      certification: '',
      position: '',
    },
    {
      employeeId: 7,
      employeeName: 'August Stranger',
      clearanceLevel: 'TOP SECRET',
      careerTrackName: 'System Admin Tier 2',
      programName: 'FBI Case Management System',
      locationName: 'Fort Belvoir VA',
      programManagerName: 'Keeley Deleon',
      interestedIn: 'Open Position: Losing Coverage 7/1/2020',
      certification: 'Linux+',
      position: 'Linux System Admin',
    },
  ];
  return employees;
}
